### ISSUE TITLE
Daily reward - Gear concerns

### ISSUE THREAD

**Issue by Joeyxxx** [kabivel/L2-SBS#8]
I'm a little worried that these daily rewards give up to S grade gear for free. It makes C/B/A redundant.

I wonder if we should remove or edit what these daily rewards give players. I want players to have to farm and craft B/A/S gear rather than being given them for free and ignoring them completely.

I suspect that you NEED S grade gear to solo farm at level 76+ so removing it from the daily rewards might be a bad idea.

What do you think?

**Comment by kabivel** [comment]
it is bad, this gear only works out for people wich just started the game, for doing raidboss they are no good. I think the gear up to grade A is sold on shops and blueprint for S gear too.

**Comment by Joeyxxx** [comment]
OK fine.

It sucks, but fine lol. B/A/S gear is awesome, I don't like the new R stuff!
